import { chromium } from "playwright";
import { writeFileSync, mkdirSync } from "node:fs";
const url = "https://mahirkurt.github.io/Dustur/";
const browser = await chromium.launch({ args: ['--ignore-certificate-errors'] });
const ctx = await browser.newContext({ deviceScaleFactor: 2, ignoreHTTPSErrors: true });
const page = await ctx.newPage();
await page.setViewportSize({ width: 1440, height: 900 });
await page.goto(url, { waitUntil: "networkidle", timeout: 30000 });
await page.evaluate(() => document.fonts.ready);
await page.waitForTimeout(800);
mkdirSync("dist/showcase", { recursive: true });
const buf = await page.screenshot({ type: "png" });
writeFileSync("dist/showcase/PROD-hero.png", buf);
console.log("PROD hero captured:", buf.length, "bytes");
await page.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight));
await page.waitForTimeout(400);
const buf2 = await page.screenshot({ type: "png" });
writeFileSync("dist/showcase/PROD-footer.png", buf2);
console.log("PROD footer captured:", buf2.length, "bytes");
await browser.close();
